const cron = require('node-cron');
const User = require('../models/User');
const Certificate = require('../models/Certificate');
const IDCard = require('../models/IDCard');
const Project = require('../models/Project');
const Contact = require('../models/Contact');
const sendEmail = require('./sendEmail');

const generateWeeklyReport = async () => {
    try {
        console.log('[Reports] Generating weekly system report...');

        const oneWeekAgo = new Date();
        oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);

        const filter = { createdAt: { $gte: oneWeekAgo } };

        // Gather metrics
        const newUsers = await User.countDocuments(filter);
        const newCerts = await Certificate.countDocuments(filter);
        const newIDCards = await IDCard.countDocuments(filter);
        const newProjects = await Project.countDocuments(filter);
        const newLeads = await Contact.countDocuments(filter);

        // Find super admins
        const superAdmins = await User.find({ role: 'super-admin' }).select('email firstName');

        if (superAdmins.length === 0) {
            console.log('[Reports] No super-admins found. Aborting report send.');
            return;
        }

        const emailHtml = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaea; border-radius: 10px;">
                <div style="text-align: center; margin-bottom: 20px;">
                    <h2 style="color: #1e5cdc; margin: 0;">Weekly System Summary</h2>
                    <p style="color: #666; margin-top: 5px;">The Contractum</p>
                </div>
                
                <p>Hello Admin,</p>
                <p>Here is your automated weekly summary of platform activity over the last 7 days:</p>
                
                <table style="width: 100%; border-collapse: collapse; margin-top: 20px; margin-bottom: 30px;">
                    <tr style="background-color: #f8fafc; border-bottom: 2px solid #e2e8f0;">
                        <th style="padding: 12px; text-align: left; color: #475569;">Metric</th>
                        <th style="padding: 12px; text-align: center; color: #475569;">Count</th>
                    </tr>
                    <tr style="border-bottom: 1px solid #f1f5f9;">
                        <td style="padding: 12px; color: #334155;"><strong>New Registrations (Users)</strong></td>
                        <td style="padding: 12px; text-align: center; font-weight: bold; color: #1e5cdc;">${newUsers}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #f1f5f9;">
                        <td style="padding: 12px; color: #334155;"><strong>Certificates Issued</strong></td>
                        <td style="padding: 12px; text-align: center; font-weight: bold; color: #1e5cdc;">${newCerts}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #f1f5f9;">
                        <td style="padding: 12px; color: #334155;"><strong>ID Cards Generated</strong></td>
                        <td style="padding: 12px; text-align: center; font-weight: bold; color: #1e5cdc;">${newIDCards}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #f1f5f9;">
                        <td style="padding: 12px; color: #334155;"><strong>New Projects Added</strong></td>
                        <td style="padding: 12px; text-align: center; font-weight: bold; color: #1e5cdc;">${newProjects}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #f1f5f9;">
                        <td style="padding: 12px; color: #334155;"><strong>New Leads/Inquiries</strong></td>
                        <td style="padding: 12px; text-align: center; font-weight: bold; color: #1e5cdc;">${newLeads}</td>
                    </tr>
                </table>

                <div style="background-color: #eff6ff; padding: 15px; border-left: 4px solid #3b82f6; border-radius: 4px;">
                    <p style="margin: 0; color: #1e3a8a; font-size: 14px;">
                        <strong>Note:</strong> Log in to the <a href="${process.env.FRONTEND_URL}/admin" style="color: #2563eb;">Admin Dashboard</a> for a complete breakdown of analytics and recent activities.
                    </p>
                </div>
                
                <p style="color: #94a3b8; font-size: 12px; text-align: center; margin-top: 30px;">
                    This is an automated system message generated by The Contractum.
                </p>
            </div>
        `;

        // Send to all super admins
        for (const admin of superAdmins) {
            await sendEmail({
                email: admin.email,
                subject: 'Weekly System Report - The Contractum',
                html: emailHtml
            });
        }

        console.log(`[Reports] Weekly report successfully sent to ${superAdmins.length} super-admin(s).`);

    } catch (err) {
        console.error('[Reports] Error generating weekly report:', err);
    }
};

const initializeReportCron = () => {
    // Schedule for every Monday at 8:00 AM (0 8 * * 1)
    cron.schedule('0 8 * * 1', () => {
        generateWeeklyReport();
    });
    console.log('[System] Weekly Report cron scheduled (Runs: Monday at 08:00 AM)');
};

module.exports = { generateWeeklyReport, initializeReportCron };
